version: '3.8'
services:
  api_server:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
        TYPE: API
        PORT: 80
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped